<section class="socials">
        <a href="https://www.linkedin.com/in/nelly-pons-1140a7131" target="_blank"><i class="fab fa-linkedin"></i></a>
        <a href="https://github.com/nelpons" target="_blank"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/nelly_pons/" target="_blank"><i class="fab fa-instagram"></i></a>
</section>

<footer class="footer">
    <p>© 2026 – Nelly Pons. All rights reserved.</p>
</footer>