<!-- HEADER MODERNE -->

<header class="header-modern">
    <nav>
        <div class="burger" id="burger">
            <span></span><span></span><span></span>
        </div>
        <a href="/index.html" class="logo">
            <img src="/assets/logos/Nelly Pons LogoWhite_vecto2.png" 
                alt="Logo de Nelly Pons" 
                class="logo-image">
        </a>
        <ul class="nav-links">
            <li><a href="/index.html" class="active">Accueil</a></li>

            <li class="dropdown">
                <a href="pages/pro/pro.html">Professionnel</a>
                <ul class="dropdown-menu">
                    <li><a href="/pages/pro/CV/cv.html">Curriculum Vitae</a></li>
                    <li><a href="/pages/pro/engagements/paris2024.html">Volontaire Paris2024</a></li>
                    <li class="dropdown-sub">
                            <a href="#">
                            Thèse de Doctorat, France - 2021/2026
                            <span class="submenu-arrow">▸</span>
                        </a>
                        <ul class="dropdown-submenu">
                            <li><a href="/pages/pro/these/main_project.html">Projet de recherche</a></li>
                            <li><a href="/pages/pro/these/conf/recapconf.html">Conférences et présentatations</a></li>
                        </ul>
                    </li>
                    <li><a href="/pages/pro/YGT_ESTEC/YGT_esa.html">Young Graduate Trainee ESA, Pays-Bas - 2020</a></li>
                    <li class="dropdown-sub">
                            <a href="#">
                            Stages pendant les études
                            <span class="submenu-arrow">▸</span>
                        </a>
                        <ul class="dropdown-submenu">
                            <li><a href="/pages/pro/pendanting/airbus_stage/airbus_stage.html">Airbus Defense & Space, Allemagne - 2019</a></li>
                            <li><a href="/pages/pro/pendanting/roumanie_stage/roumanie_stage.html">Université Politechnique de Bucarest, Roumanie -2018</a></li>
                            <li><a href="/pages/pro/pendanting/geosciences_Lyon1/geosciencesLyon1_stage.html">Université Lyon 1, France - 2017</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-sub">
                            <a href="#">
                            Awards
                            <span class="submenu-arrow">▸</span>
                        </a>
                        <ul class="dropdown-submenu">
                            <li><a href="/pages/pro/awards/innov/projet_innov'in.html">Innovatome - 2018</a></li>
                        </ul>
                    </li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="/pages/perso/index.html">Personnel</a>
                <ul class="dropdown-menu">
                    <li><a href="/pages/perso/photos/paysages/nature.html">Photos</a></li>
                    <li><a href="/pages/perso/crochet/projet_licorne.html">Crochet</a></li>
                    <li><a href="/pages/perso/saint-jacques/caminoarles/nimes2024.html">Saint‑Jacques</a></li>
                </ul>
            </li>
            
            <li><a href="/pages/en/index.html">EN</a></li>
        </ul>
    </nav>
</header>

